export const menu = [
  { menu: "Home", path: "/" },
  { menu: "About", path: "/about" },
];

export const experiences = [
  {
    title: "SDE at PayPal / Senior Consultant",
    subtitle: "Optimum Infosystem",
    description:
      "Member of PayPal’s SRE team and working as SDE here on PayPal’s SISP project. SISP is an incident submission portal of PapPal. Here I’m working on the frontend and backend of this. for backend here I’m working on node, express js and mysql and for frontend I’m using React",
    startDate: "Nov, 2022",
    endDate: "Present",
    responsibility: [
      "Designed, developed, and maintained RESTful APIs using Node.js and Express.js for seamless communication between front-end and back-end systems.",
      "Implemented middleware functions in Express.js to handle authentication, authorization, logging, error handling, and other cross-cutting concerns",
      "Integrated Node.js applications with databases such as MongoDB, MySQL, PostgreSQL, or others using libraries like Mongoose or Sequelize for efficient data storage and retrieval.",
      "Developed dynamic and interactive front-end interfaces using HTML, CSS, JavaScript, and React with Material UI, Ant Design, or React Bootstrap.",
      "Implemented state management using Redux, Redux Toolkit, or Context API in React to manage application state and ensure data consistency across components.",
      "Conducted unit tests with Jest and Enzyme for React components and performed integration testing to ensure the reliability and functionality of the application.",
      "Designed and implemented responsive web designs in React with Material UI, Ant Design, or React Bootstrap, ensuring consistent user experiences across devices.",
      "Utilized version control systems like Git for managing codebase, collaborating with team members, and tracking changes throughout the development lifecycle.",
      "Configured deployment pipelines for Node.js and Express.js applications, and automated build, test, and deployment processes using tools like Docker and CI/CD pipelines.",
      "Participated in code reviews, provided constructive feedback, and collaborated with cross-functional teams to maintain code quality, consistency, and adherence to best practices.",
      "Identified and resolved performance bottlenecks in Node.js, Express.js, and React.js applications, and optimized code for scalability and responsiveness.",
      "Implemented security best practices such as input validation, data sanitization, and protection against common vulnerabilities like XSS, CSRF, and SQL injection.",
      "Created comprehensive documentation for APIs, components, and codebase, ensuring clarity and ease of understanding for future maintenance and development.",
    ],
  },
  {
    title: "Senior Software Engineer / Full Stack Developer / Project Manager",
    subtitle: "Nadcab Labs",
    description:
      "Worked as Senior Software Developer majorly involved in developing projects from scratch using the tech stack of MERN Stack Development where my primary goal was to develop backend and frontend along with RESTful APIs.Worked with Crypto Exchange projects, where my key responsibility was to develop a trade engine for crypto exchange and backend RESTful APIs for crypto exchange along with its frontend.",
    startDate: "Sep, 2021",
    endDate: "Oct, 2022",
  },
  {
    title: "Application Developer / Full Stack Developer",
    subtitle: "uCertify",
    description:
      "Worked as Application Developer / Full Stack Developer, as uCertify is an EdTech platform where I was working on a module called Develivery Engine. This module is the core of uCertify platform as this module is responsible for conducting exams/tests on platform and running virtual labs on platform. This module was written in PHP that was very old code so my responsibility was to adopt the latest updates of PHP and refactor this module. Originally this module was written in PHP with a functional programming approach so I refactored this and adopted OOPs approach to rewrite this module entirely.",
    startDate: "Dec, 2019",
    endDate: "Sep, 2021",
  },
  {
    title: "Full Stack Developer",
    subtitle: "Web Services",
    //description: "",
    startDate: "Dec, 2017",
    endDate: "Dec, 2019",
    responsibility: [
      "Designed, developed, and maintained backend systems using PHP to handle business logic, data processing, and API integrations.",
      "Created responsive and user-friendly interfaces using Bootstrap, React, and Node.js/Express.js to deliver seamless user experiences across various devices.",
      "Built robust APIs using PHP and Node.js/Express.js to facilitate communication between frontend and backend systems, enabling seamless data exchange and integration.",
      "Integrated backend systems with databases such as MySQL or other SQL/NoSQL databases for efficient data storage, retrieval, and management.",
      "Designed visually appealing and intuitive user interfaces, ensuring a positive user experience and adherence to design standards and best practices.",
      "Implemented secure authentication and authorization mechanisms to protect user data and restrict access to sensitive functionalities.",
      "Participated in code reviews, provided feedback, and collaborated with cross-functional teams to ensure code quality, consistency, and adherence to coding standards.",
      "Configured deployment pipelines, automating build and deployment processes, and managing infrastructure using tools like Docker and CI/CD pipelines.",
      "Conducted unit tests, integration tests, and end-to-end tests to validate the functionality, performance, and reliability of the application.",
      "Created comprehensive technical documentation including code documentation, API documentation, and user manuals to facilitate maintenance, troubleshooting, and onboarding processes.",
    ],
  },
  {
    title: "Instructor / Faculty",
    subtitle: "Spectrum Technologies",
    //description: "",
    startDate: "May, 2015",
    endDate: "Dec, 2017",
    responsibility: [
      "Conducted extensive training sessions for both college students and professionals covering a diverse range of technologies, including C, C++, PHP, Laravel, Python, HTML, CSS, JavaScript, jQuery, React, and Android application development with Google Firebase.",
      "Developed and maintained training curricula to ensure alignment with industry standards and best practices, regularly updating content to reflect emerging technologies and trends.",
      "Designed and implemented hands-on exercises and projects aimed at reinforcing theoretical concepts and enhancing practical skills, fostering a deeper understanding of complex topics.",
      "Provided personalized mentoring and support to students, offering guidance and assistance in navigating challenging subjects and overcoming obstacles to learning.",
      "Administered assessments to assess student progress and performance, offering constructive feedback to promote continuous improvement and skill development.",
    ],
  },
];

export const skills = [
  { skill: "Node Js", rating: "4" },
  { skill: "Express Js", rating: "4" },
  { skill: "React Js", rating: "4" },
  { skill: "Next Js", rating: "4" },
  { skill: "Redux", rating: "4" },
  { skill: "Redux Toolkit", rating: "4" },
  { skill: "JavaScript", rating: "4" },
  { skill: "TypeScript", rating: "4" },
  { skill: "HTML/HTML5", rating: "5" },
  { skill: "CSS/CSS3", rating: "5" },
  { skill: "JQuery", rating: "4" },
  { skill: "MongoDB", rating: "4" },
  { skill: "MySQL", rating: "4" },
  { skill: "Bootstrap", rating: "5" },
  { skill: "Material UI", rating: "5" },
  { skill: "Ant Design", rating: "5" },
  { skill: "Java/Core Java", rating: "4" },
  { skill: "Spring Boot", rating: "4" },
  { skill: "Python", rating: "4" },
  { skill: "FastAPI", rating: "4" },
  { skill: "Git", rating: "4" },
  { skill: "Github", rating: "4" },
  { skill: "AWS EC2", rating: "5" },
  { skill: "AWS S3 Bucket", rating: "5" },
  { skill: "Redis", rating: "5" },
];
